---
all:
  children:
    lab:
      hosts:
        demo:
          ansible_host: 192.168.1.x
          init_user: ubuntu
          prom_role: server

    runners:
      hosts:
        demo:

    # Harbor registry credential
    harbor_registry:
      hosts:
        demo:

    # Exporter groups
    node_exporter:
      hosts:
        demo:
