[SERVICE]
    Flush         5
    Log_Level     warn
    Daemon        Off

[INPUT]
    Name              tail
    Tag               docker.<container_id>
    Tag_Regex         (?<container_id>[^/]+)$
    Path              /var/lib/docker/containers/*/*.log
    multiline.parser  docker, cri
    DB                /tmp/flb.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name   lua
    Match  docker.*
    script /fluent-bit/etc/docker_meta.lua
    call   add_container_name

[FILTER]
    Name    grep
    Match   docker.*
    Regex   container_name (node-exporter|dcgm-exporter)

[OUTPUT]
    Name        loki
    Match       *
    Host        ${LOKI_HOST}
    Port        3100
    Labels      job=docker,host=${HOSTNAME}
    label_keys  $container_name
    line_format json
